### ISSUE TITLE
Meaning of 'Unknown 3/4/5'

### ISSUE THREAD

**Issue by NardJ** [altLab/photon-resin-calibration#2]
I retrieved some extra info about some unknown fields:
- The value of unknown4 points to the starting address of the layerDefs
- The value of unknown3 points to the starting address of unknown8
- The value of unknown5 points to the starting address of unknown14

**Comment by X3msnake** [comment]
@NardJ 

Interesting :)

thanks for sharing.

Do you think we can make a template for Veles by codisec or HexEdit by Andrew Fillips

I would really like to get rid of the 010 template since it is not open source and a 30 day trial is def not free

**Comment by NardJ** [comment]
This should not be that difficult, we now only have a few bytes unaccounted for (Veles seems like quite a large program, maybe HexEdit is best). If you are interested, I used your info in my project [Photon File Utilities](https://github.com/NardJ/PhotonFileUtils).
