### ISSUE TITLE
wrong exposure time in 1-100 photon file

### ISSUE THREAD

**Issue by valentt** [altLab/photon-resin-calibration#3]
Hi,
just opened "resin-test-50u.B150.10-100.photon" with hex editor and compared it to 20-200 file and they both have 20 seconds exposure time.

Can you please double-check?

**Comment by X3msnake** [comment]
Did you donwloaded from a release of from the source?

**Comment by X3msnake** [comment]
Yep. my Bug :\

Thanks for spotting this, will have to look at this and see if there is not something else bad

**Comment by X3msnake** [comment]
Fixed on https://github.com/altLab/photon-resin-calibration/commit/f2f8224516cd8ab69d459e834c85a584e138c19c
