### ISSUE TITLE
No issue, just a request: 100u

### ISSUE THREAD

**Issue by ZappoB** [altLab/photon-resin-calibration#4]
Thank you for this tool, but can you provide a test-file for 100u (0.1mm)? This would be great.

**Comment by X3msnake** [comment]
![image](https://user-images.githubusercontent.com/11083514/46617662-2fb5de80-cb15-11e8-8b5a-d187de2f9a7b.png)

There's already a 100u version on the repo, never did a zip release, but you can download it directly on https://github.com/altLab/photon-resin-calibration

![image](https://user-images.githubusercontent.com/11083514/46617618-14e36a00-cb15-11e8-99c7-72a725d7524c.png)

**Comment by ZappoB** [comment]
Thank you very much... I just had the ZIP-file.

**Comment by X3msnake** [comment]
:+1:
